# Generated by Django 5.1.6 on 2025-04-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_semester_options_academicsession_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='is_current',
        ),
    ]
