# Generated by Django 5.1.6 on 2025-04-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_semester_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='semester',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start_date',
            field=models.DateField(),
        ),
    ]
