# Generated by Django 5.1.6 on 2025-04-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_semester_is_current_alter_semester_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={},
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='department',
            name='max_level',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_level_update',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
